import type { Metadata } from "next";
import { Barlow_Semi_Condensed } from "next/font/google";
import "./globals.sass";
import ContextProvider from "@/context/provider";
import { Suspense } from "react";

const barlowSemiCondensed = Barlow_Semi_Condensed({
  subsets: ["latin"],
  weight: ["600", "700"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={barlowSemiCondensed.className}>
        <ContextProvider>
          <Suspense>
            {children}
          </Suspense>
        </ContextProvider>
      </body>
    </html>
  );
}
